### ISSUE TITLE
Extract Data between Start and End Strings

### ISSUE THREAD

**Issue by flywire** [marlanperumal/pdf_statement_reader#30]
Seems to extract data from area between coordinates on each page after data columns found and retains rows with a balance. A better process for bank statements would be between start and end strings:

1. Search for `Account Transactions` (occurring on line before field names)
1. Extract and save field names line
1. Search for `Opening Balance` (occurring on first page before first transaction)
1. Update to search for `BALANCE BROUGHT FORWARD` (occurring on each non-first page before first transaction)
1. Read line
1. If `CLOSING BALANCE` (occurring on last page after last transaction) end
1. If `BALANCE CARRIED FORWARD` (occurring on each non-last page after last transaction) `loop to 4` until `BALANCE BROUGHT FORWARD` found
1. `save line` `loop to 4`
1. `end`

Sample [CbaBankStatement.pdf](https://github.com/marlanperumal/pdf_statement_reader/files/6565881/Commonweath.Bank.Statement.pdf) and [savings.json](https://github.com/marlanperumal/pdf_statement_reader/files/6566256/savings.json.txt)

Editable: [CbaBankStatement2.docx](https://github.com/marlanperumal/pdf_statement_reader/files/6566281/CbaBankStatement2.docx)

**Comment by flywire** [comment]
Seems to extract data from area between coordinates on each page. A better process for bank statements would be between start and end strings:

1. Search for `Account Transactions` (occuring on line before field names)
1. Extract and save field names line
1. Search for `Opening Balance` (occuring on first page before first transaction)
1. Update to search for `BALANCE BROUGHT FORWARD` (occuring on each non-first page before first transaction)
1. Read line
1. If `CLOSING BALANCE` (occuring on last page after last transaction) `end`
1. If `BALANCE CARRIED FORWARD` (occuring on each non-last page after last transaction) `loop to 4` unit `BALANCE BROUGHT FORWARD` found
1. `save line` `loop to 4`
1. `end`

**Comment by marlanperumal** [comment]
So the problem here is that the format of these bank statements is far more varied than I'd initially thought. So for example in the CBA example statement, each transaction entry can consist of 1, 2, or 3 lines and it's not exactly obvious how they should be treated. I think the best strategy is just to try to read all the data into a pandas data frame, then allow the tool to be extended by overriding a `process` method in a base class that will then handle each type. I don't think it will be easily configurable with just a json config file.

**Comment by flywire** [comment]
The approach in the code is better but parsing is not good enough.
